CC = g++
CFLAGS = -std=c++11

all: relocate_1 relocate_2 relocate_3 relocate_4

relocate_1: relocate_1.c
	$(CC) relocate_1.c $(CFLAGS) -o relocate_1

relocate_2: relocate_2.c
	$(CC) relocate_2.c $(CFLAGS) -o relocate_2

relocate_3: relocate_3.c
	$(CC) relocate_3.c $(CFLAGS) -o relocate_3

relocate_4: relocate_4.c
	$(CC) relocate_4.c $(CFLAGS) -o relocate_4

clean:
	rm -rf relocate_1 relocate_2 relocate_3 relocate_4